/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    pages: Page;
    'insights-posts': InsightsPost;
    publications: Publication;
    'optics-tools': OpticsTool;
    courses: Course;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'insights-posts': InsightsPostsSelect<false> | InsightsPostsSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    'optics-tools': OpticsToolsSelect<false> | OpticsToolsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ar' | 'fr') | ('en' | 'ar' | 'fr')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'ar' | 'fr';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'group-admin' | 'studio-editor' | 'network-editor' | 'node-admin' | 'translator';
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * e.g. merlx.org, studio.merlx.org, nilex.merlx.org
   */
  domain: string;
  displayName: string;
  type: 'group' | 'studio' | 'network' | 'node' | 'learn';
  status: 'active' | 'pre-launch' | 'archived';
  primaryLocale: 'en' | 'ar' | 'fr';
  supportedLocales?: ('en' | 'ar' | 'fr')[] | null;
  accentColor: 'teal' | 'orange' | 'sage' | 'slate' | 'deep-teal';
  tagline?: string | null;
  /**
   * Whether this tenant publishes Insights. Studio + Network always true; Nodes opt in.
   */
  hasInsights?: boolean | null;
  /**
   * e.g. merlx-blob/studio. Used to scope media uploads.
   */
  blobBucketPrefix: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * URL slug — e.g. "about", "legal/privacy"
   */
  slug: string;
  title: string;
  subtitle?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'draft' | 'published';
  /**
   * Used for OpenGraph + meta description.
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights-posts".
 */
export interface InsightsPost {
  id: number;
  tenant?: (number | null) | Tenant;
  slug: string;
  title: string;
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category: 'news' | 'analysis' | 'field-note' | 'methods';
  publishedAt: string;
  /**
   * When true, this post bubbles up to parent tenant aggregate feeds (Network → Group, Node → Network → Group).
   */
  syndicate?: boolean | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  tenant?: (number | null) | Tenant;
  slug: string;
  title: string;
  authors?:
    | {
        name: string;
        affiliation?: string | null;
        id?: string | null;
      }[]
    | null;
  year: number;
  type: 'peer-reviewed' | 'working-paper' | 'brief' | 'methodology' | 'report';
  abstract?: string | null;
  doi?: string | null;
  /**
   * URL to PDF (Vercel Blob in production).
   */
  fileUrl?: string | null;
  language?: ('en' | 'ar' | 'fr') | null;
  syndicate?: boolean | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Studio Optics Suite tool entries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "optics-tools".
 */
export interface OpticsTool {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * URL slug — e.g. "prism", "toc-tester"
   */
  slug: string;
  name: string;
  /**
   * One-liner for cards and hero.
   */
  tagline: string;
  /**
   * Short paragraph used in cards / hero.
   */
  summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Full marketing copy on /optics/[slug].
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Bullet list rendered under "Capabilities" on /optics/[slug].
   */
  capabilities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tech-stack chips rendered under "Built on" on /optics/[slug].
   */
  builtOn?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  screenshots?:
    | {
        caption?: string | null;
        /**
         * Image URL or media ID (uploads collection deferred to v1.5).
         */
        image?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'live' | 'beta' | 'coming-soon';
  /**
   * Where the live tool lives (if any). Renders the "Launch tool →" CTA.
   */
  externalUrl?: string | null;
  /**
   * e.g., "prism.merlx.org" — used by the proxy rule.
   */
  subdomain?: string | null;
  /**
   * Sort order on /optics. Lower = earlier.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Course catalogue for learn.merlx.org.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * URL slug — e.g. "conflict-sensitive-evaluation".
   */
  slug: string;
  title: string;
  /**
   * One-liner shown in the catalogue card.
   */
  tagline: string;
  track: 'cooperative-onboarding' | 'continuous-learning' | 'advanced-merl' | 'tool-training';
  audience: ('network' | 'enumerators' | 'donors' | 'ingo' | 'studio')[];
  level: 'foundation' | 'intermediate' | 'advanced';
  language: ('en' | 'ar' | 'fr' | 'es')[];
  /**
   * e.g. "4 hours self-paced", "8 weeks cohort".
   */
  duration: string;
  format: 'self-paced' | 'cohort' | 'workshop' | 'hybrid';
  /**
   * Lead instructor name (free-text for v1).
   */
  instructor?: string | null;
  instructorAffiliation?: string | null;
  prerequisites?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  learningOutcomes?:
    | {
        outcome: string;
        id?: string | null;
      }[]
    | null;
  outline?:
    | {
        title: string;
        summary?: string | null;
        /**
         * e.g. "30 minutes", "Week 2".
         */
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Long-form description on the course detail page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Issues a completion certificate. Affects copy on the detail page.
   */
  certifies?: boolean | null;
  /**
   * Whether this course is part of the floor a new Network node must complete before formal admission.
   */
  requiredForNodeAdmission?: boolean | null;
  price?: {
    model?: ('free' | 'free-network' | 'seat' | 'cohort' | 'subscription') | null;
    /**
     * e.g. "€450", "First cohort free".
     */
    amount?: string | null;
    note?: string | null;
  };
  /**
   * Set when format=cohort. Free-text for v1; promote to date fields if needed.
   */
  cohort?: {
    /**
     * e.g. "13 Oct 2026".
     */
    startsOn?: string | null;
    endsOn?: string | null;
    enrolmentDeadline?: string | null;
    /**
     * e.g. "20 participants".
     */
    cohortSize?: string | null;
  };
  status: 'open' | 'starting-soon' | 'waitlist' | 'closed' | 'coming-soon';
  /**
   * External LMS URL when wired. While unset, the website routes the CTA to /contact.
   */
  enrolmentUrl?: string | null;
  /**
   * Sort order within the catalogue. Lower = earlier.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  organisation?: string | null;
  role?: string | null;
  country?: string | null;
  message: string;
  interest?: ('studio' | 'network' | 'hosted' | 'pilot' | 'build-with' | 'advisory')[] | null;
  /**
   * Which tenant + page the submission came from (e.g., "group:/contact").
   */
  tenantOrigin: string;
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
  };
  submittedAt: string;
  status: 'new' | 'in-progress' | 'resolved' | 'spam';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'insights-posts';
        value: number | InsightsPost;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'optics-tools';
        value: number | OpticsTool;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  domain?: T;
  displayName?: T;
  type?: T;
  status?: T;
  primaryLocale?: T;
  supportedLocales?: T;
  accentColor?: T;
  tagline?: T;
  hasInsights?: T;
  blobBucketPrefix?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  slug?: T;
  title?: T;
  subtitle?: T;
  body?: T;
  status?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights-posts_select".
 */
export interface InsightsPostsSelect<T extends boolean = true> {
  tenant?: T;
  slug?: T;
  title?: T;
  excerpt?: T;
  body?: T;
  category?: T;
  publishedAt?: T;
  syndicate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  tenant?: T;
  slug?: T;
  title?: T;
  authors?:
    | T
    | {
        name?: T;
        affiliation?: T;
        id?: T;
      };
  year?: T;
  type?: T;
  abstract?: T;
  doi?: T;
  fileUrl?: T;
  language?: T;
  syndicate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "optics-tools_select".
 */
export interface OpticsToolsSelect<T extends boolean = true> {
  tenant?: T;
  slug?: T;
  name?: T;
  tagline?: T;
  summary?: T;
  description?: T;
  capabilities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  builtOn?:
    | T
    | {
        item?: T;
        id?: T;
      };
  screenshots?:
    | T
    | {
        caption?: T;
        image?: T;
        id?: T;
      };
  status?: T;
  externalUrl?: T;
  subdomain?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  tenant?: T;
  slug?: T;
  title?: T;
  tagline?: T;
  track?: T;
  audience?: T;
  level?: T;
  language?: T;
  duration?: T;
  format?: T;
  instructor?: T;
  instructorAffiliation?: T;
  prerequisites?:
    | T
    | {
        item?: T;
        id?: T;
      };
  learningOutcomes?:
    | T
    | {
        outcome?: T;
        id?: T;
      };
  outline?:
    | T
    | {
        title?: T;
        summary?: T;
        duration?: T;
        id?: T;
      };
  description?: T;
  certifies?: T;
  requiredForNodeAdmission?: T;
  price?:
    | T
    | {
        model?: T;
        amount?: T;
        note?: T;
      };
  cohort?:
    | T
    | {
        startsOn?: T;
        endsOn?: T;
        enrolmentDeadline?: T;
        cohortSize?: T;
      };
  status?: T;
  enrolmentUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  organisation?: T;
  role?: T;
  country?: T;
  message?: T;
  interest?: T;
  tenantOrigin?: T;
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
      };
  submittedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}